# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="ys"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-flow github alias-tips mvn colorize colored-man-pages tmux tmuxinator vi-mode docker brew osx sublime zsh-syntax-highlighting jsontools zsh-autosuggestions zsh-syntax-highlighting)

# User configuration
export LANG=en_US.UTF-8
export LESSCHARSET=utf-8
export PATH=~/.local/bin:$PATH
export RIPGREP_CONFIG_PATH=~/.ripgreprc

# Preferred editor for local and remote sessions
export EDITOR=vim

# Key binding
bindkey -v
# bindkey '^A' beginning-of-line
# bindkey '^E' end-of-line
# bindkey "\e\e[D" backward-word
# bindkey "\e\e[C" forward-word

# 10ms for key sequences
KEYTIMEOUT=1

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
alias mv='mv -i'
alias cp='cp -i'
alias weather='curl wttr.in'
alias cb='xclip -sel clip'
alias gla='git log --graph --pretty='\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --all -20'

source $ZSH/oh-my-zsh.sh

# os dependent
[ -f "${HOME}/.zshrc-`uname`" ] && source "${HOME}/.zshrc-`uname`"


# init pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source /usr/local/opt/autoenv/activate.sh

# init z
[[ -r "/usr/local/etc/profile.d/z.sh"  ]] && . /usr/local/etc/profile.d/z.sh
[[ -r "/usr/share/z/z.sh"  ]] && source /usr/share/z/z.sh

# init fzf
[ -f ~/.fzf.zsh  ] && source ~/.fzf.zsh
[ -f /usr/share/fzf/completion.zsh ] && source /usr/share/fzf/completion.zsh
[ -f /usr/share/fzf/key-bindings.zsh ] && source /usr/share/fzf/key-bindings.zsh
export FZF_DEFAULT_OPTS='--height 40% --border --multi --preview="head -10 {+}"'

# init rbenv
eval "$(rbenv init -)"

# tmux as default
#if [ -z "$TMUX" ]; then
#    tmux attach -t default || tmux new -s default
#fi

function watch2 () {
    while :; do 
        hdr="$(clear; date) >> $@\n\n"; 
        res=$(eval $@ 2>&1); 
        echo "$hdr$res"; 
        sleep 1;  
    done
}

