--- 

- name: set zsh as default
  user: 
    name: "{{ ansible_env.USER }}" 
    shell: "{{ zsh_path }}"
  when: zsh_path is defined
  become: yes
  ignore_errors: yes

- name: copy zshrc
  template: 
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
    backup: yes
  with_items:
    - zshrc

- name: clone oh-my-zsh repo
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ ansible_env.HOME }}/.oh-my-zsh

- name: clone themes
  git : repo=https://github.com/{{ item.account }}/{{ item.repo }}.git 
        dest={{ ansible_env.HOME }}/.oh-my-zsh/themes/{{ item.dest }}
  with_items:
    - { account: "dracula", repo: "zsh", dest: "dracula" }
    - { account: "romkatv", repo: "powerlevel10k", dest: "powerlevel10k" }
    - { account: "denysdovhan", repo: "spaceship-prompt", dest: "spaceship" }

- name: custom plugins 
  git: repo=https://github.com/{{ item.account }}/{{ item.repo }}.git
       dest=~/.oh-my-zsh/custom/plugins/{{ item.repo }}
  with_items:
    - { account: "zsh-users", repo: "zsh-autosuggestions" }
    - { account: "zsh-users", repo: "zsh-syntax-highlighting" }
    - { account: "Aloxaf", repo: "fzf-tab" }

- name: zsh custom lib dir 
  file: 
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/lib"
    state: directory

- name: override misc.sh 
  template: src=misc.zsh dest="{{ ansible_env.HOME }}/.oh-my-zsh/custom/lib/" backup=yes

- name: ripgreprc
  template: src=ripgreprc dest="{{ ansible_env.HOME }}/.ripgreprc" backup=yes
